sonar.organization=nehal-wandhare
sonar.projectKey=nehal-wandhare_python-devsecops-demo
sonar.projectName=Python DevSecOps Demo

sonar.sources=app.py,static,templates
sonar.tests=tests

sonar.exclusions=venv/**,.git/**,.pytest_cache/**,htmlcov/**,reports/**,coverage.xml

sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300